version: '3'

services:
    frontend:
        build: bases-app/.
        container_name: bases-app
        ports: 
            - '80:80'
        volumes:
            - '.:/bases-app/app'
        networks: 
            app-net:
                ipv4_address: 172.19.0.2
    
    backend:
        build: bases-flask/.
        container_name: bases-flask
        ports: 
            - '5000:5000'
        volumes:
            - '.:/bases-flask/code'
        networks: 
            app-net:
                ipv4_address: 172.19.0.3
    
    database:
        image: mysql:latest
        
        container_name: bases-db
        ports: 
            - '3306:3306'
        environment: 
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: P2Bases
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            - database:/var/lib/mysql
        networks: 
            app-net:
                ipv4_address: 172.19.0.4

networks:
    app-net:
        ipam:
            driver: default
            config:
            - subnet: "172.19.0.0/24"

volumes:
    database: